### ISSUE TITLE
you da bomb

### ISSUE THREAD

**Issue by zvory** [hmexx/vue_typescript_starter_kit#1]
thanks for making this :heart:

**Comment by zvory** [comment]
https://github.com/kaorun343/vue-property-decorator

this might be useful to add if you ever want props to be of complex/TypeScript defined types.

**Comment by hmexx** [comment]
Thanks dude. Thought i'd finally put SOMETHING on github, even if it is just boilerplate code, lol.

I'll revisit it in a couple of weeks when I start a real Vue project for work, at which point I will the add decorators.

**Comment by hmexx** [comment]
thanks for the heads up about the email address. i deleted the git history.
