### ISSUE TITLE
How to write a getter that takes an input argument in TypeScript?

### ISSUE THREAD

**Issue by mmakrzem** [hmexx/vue_typescript_starter_kit#2]
I have a getter that needs to accept a parameter, but I can't figure out a way to write that in TypeScript.  The following does not work.

```
export function getItemById(state : State, id : Number) : MyItem | undefined {
  if(id === undefined) {
    return undefined;
  }
  for(const item of state.items) {
    if(item.id === id) {
      return item;
    }
  }
  return undefined;
}

export default <GetterTree<State, any>> {
  getItemById
};
```

**Comment by hmexx** [comment]
Hi Marek.

I'm actually also not experienced in Vue, so you may want to ask elsewhere, but maybe try the following:

`const getItemById = function (state : State, id : Number) : MyItem | undefined {
  if(id === undefined) {
    return undefined;
  }
  for(const item of state.items) {
    if(item.id === id) {
      return item;
    }
  }
  return undefined;
}

const getters:GetterTree<State,any> = {
  getItemById: getItemById

}

export default new Vuex.Store<State>({
  getters,
  state,
  mutations,
  actions
});`

**Comment by mmakrzem** [comment]
Same problem.  I'm getting an error that says **this.$store.getters.getCommand** is undefined

**Comment by zvory** [comment]
Getters should return functions that take arguments if I recall correctly?

**Comment by mmakrzem** [comment]
Thanks @zvory,  I couldn't get your syntax working in my project but the syntax shown here (https://stackoverflow.com/questions/47163495/vuex-getter-with-argument-written-in-typescript) works for me.
